import React from 'react';
import './Flashcards.css';

const Flashcards = ({ cards = [], noteTitle = 'Note' }) => {
  return (
    <div className="flashcards-root">
      <header className="flash-header">
        <h2>🃏 Flashcards — {noteTitle}</h2>
        <p className="muted">Placeholder cards generated by AI (backend integration later)</p>
      </header>

      <div className="cards-grid">
        {cards.map((c, i) => (
          <div key={i} className="card">
            <div className="front">{c.q}</div>
            <div className="back">{c.a}</div>
          </div>
        ))}
      </div>

      <footer className="flash-footer">
        <button className="btn-primary" onClick={() => alert('Save flashcards (placeholder)')}>Save to Library</button>
        <button className="btn-ghost" onClick={() => alert('Study mode (placeholder)')}>Start Study</button>
      </footer>
    </div>
  );
};

export default Flashcards;